frontend/lib/frontend_web/router.ex
defmodule FrontendWeb.Router do
  use FrontendWeb, :router

  import Phoenix.LiveView.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_root_layout, {FrontendWeb.LayoutView, :root}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :authenticated do
    plug FrontendWeb.Plugs.AuthenticatedPipeline
  end

  pipeline :unauthenticated do
    plug FrontendWeb.Plugs.UnauthenticatedPipeline
  end

  scope "/", FrontendWeb do
    pipe_through :browser

    get "/", PageController, :new
  end

  # Other scopes may use custom stacks.
  # scope "/api", FrontendWeb do
  #   pipe_through :api
  # end

  scope "/", FrontendWeb do
    pipe_through [:browser, :unauthenticated]

    get("/ping", PingController, :show)

    get "/signup", RegistrationController, :new
    post "/signup", RegistrationController, :create

    get "/signin", SessionController, :new
    post "/signin", SessionController, :create

    get "/signout", SessionController, :delete

    get "/test", SessionController, :test
  end

  scope "/boards", FrontendWeb do
    pipe_through [:browser, :authenticated]

    resources "/", BoardController
  end

  # scope "/", FrontendWeb do
  #   pipe_through :browser

  #   post "/signup", AccountController, :create
  #   post "/signin", AccountController, :signin
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: FrontendWeb.Telemetry
    end
  end
end

frontend/lib/frontend/api/session.ex
defmodule Frontend.API.Session do
  use Tesla

  alias Ecto.Changeset

  alias Frontend.Schemas.User
  alias Frontend.API.Session

  @success_codes 200..399

  def change_user_signin(%User{} = user, attrs \\ %{}) do
    User.signin_changeset(user, attrs)
  end

  def create_session(params) do
    url = "/signin"

    with %{valid?: true} = changeset <- User.signin_changeset(%User{}, params),
         user <- Changeset.apply_changes(changeset),
         client <- client(),
         {:ok, %{body: body, status: status}} when status in @success_codes
          <- Tesla.post(client, url, user) do
          # %{"user"=>user, "token"=>token} = body
      {:ok, from_response(body)}
    else
      {:ok, %{body: body}} -> {:error, body}
      %Changeset{} = changeset -> {:error, changeset}
      error -> error
    end
  end

  def delete_session(params) do
    url = "/signout"
    {access_token, _params} = Map.pop(params, "access_token")

    with client <- client(access_token),
         {:ok, %{body: body, status: status}} when status in @success_codes
          <- Tesla.post(client, url) do
          # %{"user"=>user, "token"=>token} = body
      {:ok, from_response(body)}
    else
      {:ok, %{body: body}} -> {:error, body}
      %Changeset{} = changeset -> {:error, changeset}
      error -> error
    end
  end

  defp from_response(%{"user"=>user, "token"=>token}) do
    changeset = %User{}
    |> User.changeset(user)
    |> Changeset.apply_changes()

    %{user: changeset, token: token }
  end

  def client() do
    url = Application.get_env(:frontend, :api_url)

    middleware = [
      {Tesla.Middleware.BaseUrl, url},
      Tesla.Middleware.JSON,
      Tesla.Middleware.PathParams
    ]

    Tesla.client(middleware)
  end

  def client(access_token) do
    url = Application.get_env(:frontend, :api_url)

    middleware = [
      {Tesla.Middleware.BaseUrl, url},
      Tesla.Middleware.JSON,
      Tesla.Middleware.PathParams,
      {Tesla.Middleware.Headers, [{"Authorization", "Bearer #{access_token}"}]},
    ]

    Tesla.client(middleware)
  end
end

frontend/lib/frontend_web/controllers/session_controller.ex
defmodule FrontendWeb.SessionController do
  use FrontendWeb, :controller

  alias Phoenix.LiveView
  alias Frontend.API.Session
  alias Frontend.Schemas.User

  # plug :scrub_params, "session" when action in ~w(create)a

  def new(conn, _params) do
    changeset = Session.change_user_signin(%User{})

    conn
    |> put_layout(false) # disable app.html.eex layout
    |> put_root_layout(false) # disable root.html.eex layout
    |> render("signin.html", changeset: changeset)
  end

  def create(conn, %{"user" => user}) do
    case Session.create_session(user) do
      {:ok, %{user: user, token: token}} ->
        conn
        |> put_session(:user, user)
        |> put_session(:access_token, token)
        |> put_flash(:info, "Successfully logged in.")
        |> redirect(to: Routes.board_path(conn, :index))
      {:error, _params} ->
        changeset = Session.change_user_signin(%User{})
        conn
        |> put_flash(:error, "Failed to log in.")
        |> render("signin.html", changeset: changeset)
    end
  end

  def test(conn, _params) do
    conn
    |> put_layout(false) # disable app.html.eex layout
    |> put_root_layout(false) # disable root.html.eex layout
    |> render("test.html")
  end

  def delete(conn, _params) do
    conn
    |> delete_session(:user)
    |> delete_session(:token)
    |> put_flash(:info, "See you again soon!")
    |> redirect(to: Routes.session_path(conn, :new))
  end

  # def signup(conn, test) do
  #   changeset = Users.change_user(%User{})

  #   conn
  #   |> put_layout(false) # disable app.html.eex layout
  #   |> put_root_layout(false) # disable root.html.eex layout
  #   |> render("signup.html", changeset: changeset)
  # end

  # def signin(conn, test) do
  #   conn
  #   |> put_layout(false) # disable app.html.eex layout
  #   |> put_root_layout(false) # disable root.html.eex layout
  #   |> render("signin.html")
  # end

  # use BackendWeb, :controller

  # plug :scrub_params, "session" when action in ~w(create)a

  # def new(conn, _) do
  #   render conn, "new.html"
  # end

  # def create(conn, %{"session" => %{"email" => email, "password" => password}}) do

  #   # here will be an implementation
  # end

  # def delete(conn, _) do
  #   # here will be an implementation
  # end
end

frontend/lib/frontend_web/views/session_view.ex
defmodule FrontendWeb.SessionView do
  use FrontendWeb, :view
end

frontend/lib/frontend_web/templates/session/signin.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Trello</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>

    <!-- Fontawesome -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    
    <!-- Title -->
    <link href="https://fonts.googleapis.com/css?family=Chivo:300,700|Playfair+Display:700i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">

    <!-- Description -->
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">

    <%= csrf_meta_tag() %>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <main role="main" class="container">
      <%= if get_flash(@conn, :info) != nil or get_flash(@conn, :error) != nil do %>
        <div class="alert <%= if get_flash(@conn, :info) != nil do %>alert-success<% else %>alert-danger<% end %>" role="alert">
          <strong class="font-bold">Success</strong>
          <span class="block sm:inline"><%= if get_flash(@conn, :info), do: get_flash(@conn, :info), else: get_flash(@conn, :error) %></span>
          <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
            <svg class="fill-current h-6 w-6 text-green-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
          </span>
        </div>
      <% end %>
      <div class="grid grid-cols-1 place-items-end">
          <div class="place-self-end">
          </div>
      </div>
      <div class="min-h-screen flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
        <div class="max-w-md w-full space-y-8">
          <div>
            <!--
            <img class="mx-auto h-12 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg" alt="Workflow">
            -->
            <h2 class="mt-6 text-center text-3xl font-extrabold text-white">
              Sign in to your account
            </h2>
            <p class="mt-2 text-center text-sm text-white-600">
              or
              <%= link to: Routes.registration_path(@conn, :new), class: "font-medium" do %>
                  Signup
              <% end %>
            </p>
          </div>
          <%= form_for @changeset, Routes.session_path(@conn, :create), [class: "mt-8 space-y-6"],fn f -> %>
            <%= if @changeset.action do %>
              <div class="alert alert-danger">
                <p>Oops, something went wrong! Please check the errors below.</p>
              </div>
            <% end %>
            <input type="hidden" name="remember" value="true">
            <div class="rounded-md shadow-sm -space-y-px">
            <div>
                <%= label f, :email, class: "sr-only"%>
                <%= text_input f, :email, placeholder: "Email Address", class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" %>
            </div>
            <div>
                <%= label f, :password, class: "sr-only"%>
                <%= password_input f, :password, placeholder: "Password", class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" %>
            </div>
            </div>
            <div>
            <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-violet-500 hover:bg-violet-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                <span class="absolute left-0 inset-y-0 flex items-center pl-3">
                <!-- Heroicon name: solid/lock-closed -->
                <svg class="h-5 w-5 text-violet-900 group-hover:text-indigo-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd" />
                </svg>
                </span>
                Sign in
            </button>
            </div>
          <% end %>
        </div>  
      </div>
    </main>
  </body>
</html>

frontend/lib/frontend_web/templates/session/test.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Trello</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>

    <!-- Fontawesome -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    
    <!-- Title -->
    <link href="https://fonts.googleapis.com/css?family=Chivo:300,700|Playfair+Display:700i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">

    <!-- Description -->
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">

    <%= csrf_meta_tag() %>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <main role="main">
        <div class="main-container">
            <div class="navbar">
                <div class="search-bar">
                    <button class="home-btn">
                        <svg class="fill-current text-white h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50"><path d="M41 4H9C6.24 4 4 6.24 4 9v32c0 2.76 2.24 5 5 5h32c2.76 0 5-2.24 5-5V9c0-2.76-2.24-5-5-5zM21 36c0 1.1-.9 2-2 2h-7c-1.1 0-2-.9-2-2V12c0-1.1.9-2 2-2h7c1.1 0 2 .9 2 2v24zm19-12c0 1.1-.9 2-2 2h-7c-1.1 0-2-.9-2-2V12c0-1.1.9-2 2-2h7c1.1 0 2 .9 2 2v12z"/></svg>
                        Boards
                    </button>
                    <input type="text" class="search-input">
                </div>
                <div class="pageTitle-container">
                    <h1 class="page-title">
                        <svg class="fill-current h-8 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50"><path d="M41 4H9C6.24 4 4 6.24 4 9v32c0 2.76 2.24 5 5 5h32c2.76 0 5-2.24 5-5V9c0-2.76-2.24-5-5-5zM21 36c0 1.1-.9 2-2 2h-7c-1.1 0-2-.9-2-2V12c0-1.1.9-2 2-2h7c1.1 0 2 .9 2 2v24zm19-12c0 1.1-.9 2-2 2h-7c-1.1 0-2-.9-2-2V12c0-1.1.9-2 2-2h7c1.1 0 2 .9 2 2v12z"/></svg>
                        Trello
                    </h1>
                </div>
                <div class="profile-bar">
                    <button class="profile-btn">+</button>
                    <button class="profile-btn">i</button>
                    <!--
                    <button class="notification-bell">
                        <svg class="h-4 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 2c-.8 0-1.5.7-1.5 1.5v.688C7.344 4.87 5 7.62 5 11v4.5l-2 2.313V19h18v-1.188L19 15.5V11c0-3.379-2.344-6.129-5.5-6.813V3.5c0-.8-.7-1.5-1.5-1.5zm-2 18c0 1.102.898 2 2 2 1.102 0 2-.898 2-2z"/></svg>
                    </button>
                    <img src="https://i.imgur.com/OZaT7jl.png" class="rounded-full" />
                    -->
                </div>
            </div>
            <div class="board-header">
                <div class="flex">
                    <h3 class="board-title">TailwindComponents.com</h3>
                    <!--
                    <ul class="list-reset text-white hidden md:flex">
                        <li><span class="font-bold text-lg px-2">☆</span></li>
                        <li><span class="border-l border-blue-lighter px-2 text-sm">Business Name</span> <span class="rounded-lg bg-blue-light text-xs px-2 py-1">Free</span></li>
                        <li><span class="border-l border-blue-lighter px-2 text-sm ml-2">Team Visible</span></li>
                    </ul>
                    -->
                </div>
                <div class="showMenu-btn">
                    <svg class="h-4 fill-current text-white cursor-pointer mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M5 10a1.999 1.999 0 1 0 0 4 1.999 1.999 0 1 0 0-4zm7 0a1.999 1.999 0 1 0 0 4 1.999 1.999 0 1 0 0-4zm7 0a1.999 1.999 0 1 0 0 4 1.999 1.999 0 1 0 0-4z"/></svg>
                    Show menu
                </div>
            </div>
            <div class="board">
                <div class="list-container">
                    <div class="list-header">
                        <h3 class="list-title">New landing page</h3>
                        <svg class="list-ellipsis" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M5 10a1.999 1.999 0 1 0 0 4 1.999 1.999 0 1 0 0-4zm7 0a1.999 1.999 0 1 0 0 4 1.999 1.999 0 1 0 0-4zm7 0a1.999 1.999 0 1 0 0 4 1.999 1.999 0 1 0 0-4z"/></svg>
                    </div>
                    <div class="list-body">
                        <div class="card">
                            Do a mobile first layout
                        </div>
                        <!--
                        <div class="card">
                            Check the meta tags
                        </div>
                        
                        <div class="card">
                            Check the responsive layout on all devices
                            <div class="text-grey-darker mt-2 ml-2 flex justify-between items-start">
                                <span class="text-xs flex items-center">
                                    <svg class="h-4 fill-current mr-1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50"><path d="M11 4c-3.855 0-7 3.145-7 7v28c0 3.855 3.145 7 7 7h28c3.855 0 7-3.145 7-7V11c0-3.855-3.145-7-7-7zm0 2h28c2.773 0 5 2.227 5 5v28c0 2.773-2.227 5-5 5H11c-2.773 0-5-2.227-5-5V11c0-2.773 2.227-5 5-5zm25.234 9.832l-13.32 15.723-8.133-7.586-1.363 1.465 9.664 9.015 14.684-17.324z"/></svg>
                                    3/5
                                </span>
                                <img src="https://i.imgur.com/OZaT7jl.png" class="rounded-full" />
                            </div>
                        </div>
                        -->
                        <p class="mt-3 text-grey-dark">Add a card...</p>
                    </div>
                </div>
                <div class="list-container">
                    <div class="list-header">
                        <h3 class="list-title">Old landing</h3>
                        <svg class="list-ellipsis" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M5 10a1.999 1.999 0 1 0 0 4 1.999 1.999 0 1 0 0-4zm7 0a1.999 1.999 0 1 0 0 4 1.999 1.999 0 1 0 0-4zm7 0a1.999 1.999 0 1 0 0 4 1.999 1.999 0 1 0 0-4z"/></svg>
                    </div>
                    <div class="list-body">
                        <div class="card">
                            Delete all references from the wiki
                        </div>
                        <!--
                        <div class="card">
                            Remove analytics code
                        </div>
                        
                        <div class="card">
                            Whatever
                        </div>
                        
                        <div class="card">
                            <p>Think more tasks for this example</p>
                            <div class="bg-red rounded p-1 mt-2 inline-flex text-white text-xs">
                                <svg class="h-4 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 2c-.8 0-1.5.7-1.5 1.5v.688C7.344 4.87 5 7.62 5 11v4.5l-2 2.313V19h18v-1.188L19 15.5V11c0-3.379-2.344-6.129-5.5-6.813V3.5c0-.8-.7-1.5-1.5-1.5zm-2 18c0 1.102.898 2 2 2 1.102 0 2-.898 2-2z"/></svg>
                                2
                            </div>
                        </div>
                        -->
                        <p class="mt-3 text-grey-dark">Add a card...</p>
                    </div>
                </div>
                <div class="list-container">
                    <div class="list-header">
                        <h3 class="list-title">Do more cards</h3>
                        <svg class="list-ellipsis" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M5 10a1.999 1.999 0 1 0 0 4 1.999 1.999 0 1 0 0-4zm7 0a1.999 1.999 0 1 0 0 4 1.999 1.999 0 1 0 0-4zm7 0a1.999 1.999 0 1 0 0 4 1.999 1.999 0 1 0 0-4z"/></svg>
                    </div>
                    <div class="list-body">
                        <div class="card">
                            Delete all references from the wiki
                        </div>
                        <!--
                        <div class="card">
                            Remove analytics code
                        </div>
                        
                        <div class="card">
                            Whatever
                        </div>
                        
                        <div class="card">
                            Delete all references from the wiki
                        </div>
                        
                        <div class="card">
                            Remove analytics code
                        </div>
                        
                        <div class="card">
                            Whatever
                        </div>
                        
                        <div class="card">
                            <p>Think more tasks for this example</p>
                            <div class="bg-red rounded p-1 mt-2 inline-flex text-white text-xs">
                                <svg class="h-4 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 2c-.8 0-1.5.7-1.5 1.5v.688C7.344 4.87 5 7.62 5 11v4.5l-2 2.313V19h18v-1.188L19 15.5V11c0-3.379-2.344-6.129-5.5-6.813V3.5c0-.8-.7-1.5-1.5-1.5zm-2 18c0 1.102.898 2 2 2 1.102 0 2-.898 2-2z"/></svg>
                                2
                            </div>
                        </div>
                        
                        <div class="card">
                            Delete all references from the wiki
                        </div>
                        
                        <div class="card">
                            Remove analytics code
                        </div>
                        
                        <div class="card">
                            Whatever
                        </div>
                        -->
                        <p class="addCard-btn">Add a card...</p>
                    </div>
                </div>
            </div>
        </div>
    </main>