frontend/lib/frontend_web/router.ex
defmodule FrontendWeb.Router do
  use FrontendWeb, :router

  import Phoenix.LiveView.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_root_layout, {FrontendWeb.LayoutView, :root}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :authenticated do
    plug FrontendWeb.Plugs.AuthenticatedPipeline
  end

  pipeline :unauthenticated do
    plug FrontendWeb.Plugs.UnauthenticatedPipeline
  end

  scope "/", FrontendWeb do
    pipe_through :browser

    get "/", PageController, :new
  end

  # Other scopes may use custom stacks.
  # scope "/api", FrontendWeb do
  #   pipe_through :api
  # end

  scope "/", FrontendWeb do
    pipe_through [:browser, :unauthenticated]

    get("/ping", PingController, :show)

    get "/signup", RegistrationController, :new
    post "/signup", RegistrationController, :create

    get "/signin", SessionController, :new
    post "/signin", SessionController, :create

    get "/signout", SessionController, :delete

    get "/test", SessionController, :test
  end

  scope "/boards", FrontendWeb do
    pipe_through [:browser, :authenticated]

    resources "/", BoardController
  end

  # scope "/", FrontendWeb do
  #   pipe_through :browser

  #   post "/signup", AccountController, :create
  #   post "/signin", AccountController, :signin
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: FrontendWeb.Telemetry
    end
  end
end

frontend/lib/frontend_web/views/layout_view.ex
defmodule FrontendWeb.LayoutView do
  use FrontendWeb, :view
end

frontend/lib/frontend_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Trello</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>

    <!-- Fontawesome -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    
    <!-- Title -->
    <link href="https://fonts.googleapis.com/css?family=Chivo:300,700|Playfair+Display:700i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">

    <!-- Description -->
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">

    <%= csrf_meta_tag() %>
  </head>
  <body>
    <main role="main">
      <div class="main-container">
        <%# TODO: Hide if no current user%>
        <%= render("navbar.html", assigns) %>
        <hr/>
        <%= @inner_content %>
      </div>
    </main>
  </body>
</html>

frontend/lib/frontend_web/templates/layout/live.html.leex
<%= if live_flash(@flash, :info) != nil do %>
  <div id="flash" class="flash-box" role="alert">
    <div class="alert -success">
      <div class="alert-header-icon">
        <i class="ion-md-checkmark-circle-outline"></i>
      </div>
      <div class="alert-content" phx-click="lv:clear-flash" phx-value-key="info">
        <div class="title"><%= live_flash(@flash, :info) %></div>
      </div>
    </div>
  </div>
<% end %>

<%= if live_flash(@flash, :error) != nil do %>
  <div id="flash" class="flash-box" role="alert">
    <div class="alert -error">
      <div class="alert-header-icon">
        <i class="ion-ios-alert-outline"></i>
      </div>
      <div class="alert-content" phx-click="lv:clear-flash" phx-value-key="info">
        <div class="title"><%= live_flash(@flash, :error) %></div>
      </div>
    </div>
  </div>
<% end %>

<%= @inner_content %>

frontend/lib/frontend_web/templates/layout/navbar.html.eex
<div class="navbar">
    <div class="search-bar">
        <button class="home-btn">
            <svg class="fill-current text-white h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50"><path d="M41 4H9C6.24 4 4 6.24 4 9v32c0 2.76 2.24 5 5 5h32c2.76 0 5-2.24 5-5V9c0-2.76-2.24-5-5-5zM21 36c0 1.1-.9 2-2 2h-7c-1.1 0-2-.9-2-2V12c0-1.1.9-2 2-2h7c1.1 0 2 .9 2 2v24zm19-12c0 1.1-.9 2-2 2h-7c-1.1 0-2-.9-2-2V12c0-1.1.9-2 2-2h7c1.1 0 2 .9 2 2v12z"/></svg>
            <%= link to: Routes.board_path(@conn, :index) do %>Boards<% end %>
        </button>
        <%# <input type="text" class="search-input"> %>
    </div>
    <div class="pageTitle-container">
        <h1 class="page-title">
            <svg class="fill-current h-8 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50"><path d="M41 4H9C6.24 4 4 6.24 4 9v32c0 2.76 2.24 5 5 5h32c2.76 0 5-2.24 5-5V9c0-2.76-2.24-5-5-5zM21 36c0 1.1-.9 2-2 2h-7c-1.1 0-2-.9-2-2V12c0-1.1.9-2 2-2h7c1.1 0 2 .9 2 2v24zm19-12c0 1.1-.9 2-2 2h-7c-1.1 0-2-.9-2-2V12c0-1.1.9-2 2-2h7c1.1 0 2 .9 2 2v12z"/></svg>
            Trello
        </h1>
    </div>
    <div class="profile-bar">
        <!--
        <button class="profile-btn">+</button>
        <button class="profile-btn">i</button>
        <button class="notification-bell">
            <svg class="h-4 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12 2c-.8 0-1.5.7-1.5 1.5v.688C7.344 4.87 5 7.62 5 11v4.5l-2 2.313V19h18v-1.188L19 15.5V11c0-3.379-2.344-6.129-5.5-6.813V3.5c0-.8-.7-1.5-1.5-1.5zm-2 18c0 1.102.898 2 2 2 1.102 0 2-.898 2-2z"/></svg>
        </button>
        -->
        <%# TODO: Add behavior - edit user %>
        <button type="button" class="dropdown bg-violet-800 text-gray-200 hover:text-gray-100 rounded-full h-10 w-10 flex items-center justify-center font-bold cursor-pointer">
            <%= get_first_charac_string(@conn.private.plug_session["user"].name) %>
        </button>
        <div class="opacity-0 invisible dropdown-menu transition-all duration-300 transform origin-top-right -translate-y-2 scale-95 bg-violet-300">
            <div class="absolute right-0 w-56 mt-6 origin-top-right bg-violet-300 border-violet divide-y divide-gray-100 rounded-md shadow-lg outline-none" aria-labelledby="headlessui-menu-button-1" id="headlessui-menu-items-117" role="menu">
                <div class="px-4 py-3">         
                    <p class="text-sm leading-5">Signed in as</p>
                    <p class="text-sm font-medium leading-5 text-gray-900 truncate"><%= get_current_user_email(@conn) %></p>
                </div>
                <div class="py-1">
                    <a href="javascript:void(0)" tabindex="0" class="text-gray-700 flex justify-between w-full px-4 py-2 text-sm leading-5 text-left"  role="menuitem" >Account settings</a>
                    <%# <span role="menuitem" tabindex="-1" class="flex justify-between w-full px-4 py-2 text-sm leading-5 text-left text-gray-700 cursor-not-allowed opacity-50" aria-disabled="true">New feature (soon)</span> %>
                </div>
                <div class="py-1">
                    <%= link to: Routes.session_path(@conn, :delete), tabindex: "3", class: "text-gray-700 flex justify-between w-full px-4 py-2 text-sm leading-5 text-left", role: "menuitem" do %>
                        Sign out
                    <% end %>
                </div>
            </div>
        </div>
        <!--
        <img src="https://i.imgur.com/OZaT7jl.png" class="rounded-full" />
        -->
    </div>
</div>

frontend/lib/frontend_web/templates/layout/root.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "MyApp" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    
    <!-- Fontawesome -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    
    <!-- Title -->
    <link href="https://fonts.googleapis.com/css?family=Chivo:300,700|Playfair+Display:700i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">

    <!-- Description -->
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">

    <script phx-track-static defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <%= @inner_content %>
  </body>
</html>